cc_library(
    name = 'rpc_client',
    srcs = 'rpc_client.cc',
    deps = ['//base:base',
            '//protorpc/http_client:http_client',
            '//protorpc/rpc_server:rpc_controller',
            '//thirdparty/protobuf:protobuf',
            ],
)
